;; Init package
(setq te (time-to-seconds (current-time)))
(require 'package)
(add-to-list 'package-archives (cons "melpa" "https://melpa.org/packages/") t)
(package-initialize)
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (setq packages '(lsp-ui cargo racer flycheck-rust use-package rust-mode rainbow-delimiters projectile org-bullets neotree multiple-cursors magit howdoi haskell-mode flycheck diminish dashboard company))
  (mapc (lambda (x) (unless (package-installed-p x)
                 (package-install x))) packages))

(require 'use-package)
(message "Init time for %s: %s" "loading package and melpa" (- (time-to-seconds (current-time)) te))

(setq te (time-to-seconds (current-time)))
(setq inits-dir "~/.emacs.d/inits/")
(setq inits (directory-files-recursively inits-dir ".*\.el$"))
(message "Init time for %s: %s" "listing inits" (- (time-to-seconds (current-time)) te))
(mapc (lambda (x) (let ((te (time-to-seconds (current-time))))
		    (load x)
		    (message "Init time for %s: %s" x (- (time-to-seconds (current-time)) te)))) inits)
